TravelAgency.Web/Controllers/ItinerariesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TravelAgency.Domain.Enumeration;
using TravelAgency.Domain.Models;
using TravelAgency.Repository;
using TravelAgency.Repository.Implementation;
using TravelAgency.Service.Interface;

namespace TravelAgency.Web.Controllers
{
    
    public class ItinerariesController : Controller
    {
        private readonly IItinerariesSevice itinerariesSevice;
        private readonly ITravelPackagesService travelPackagesService;
        private readonly IItineraryInPackageService itineraryInPackage;

        public ItinerariesController(IItinerariesSevice itinerariesSevice, ITravelPackagesService travelPackagesService, IItineraryInPackageService travelInPackageService)
        {
            this.itinerariesSevice = itinerariesSevice;
            this.travelPackagesService = travelPackagesService;
            this.itineraryInPackage = travelInPackageService;
        }





        // GET: Itineraries
        [Authorize(Roles = "Admin")]
        public IActionResult Index()
        {
            return View(itinerariesSevice.ListAllItineraries());
        }

        // GET: Itineraries/Details/5
        public IActionResult Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itineraries = itinerariesSevice.GetItinerariesById(id);
               
            if (itineraries == null)
            {
                return NotFound();
            }

            return View(itineraries);
        }

        // GET: Itineraries/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            List<SelectListItem> packages = travelPackagesService.ListAllPackages().Select(t => new SelectListItem
                       {
                           Text = t.Name,
                           Value = t.Id.ToString(),
                       }).ToList();

            ViewData["packages"] = packages;
            return View();
        }

        // POST: Itineraries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public  IActionResult Create([Bind("Name,Description,DayNumber,Place,Image,ArivalTime,DepartutreTime,Id")] Itineraries itineraries, List<Guid> Packages)
        {
           
            if (ModelState.IsValid)
            {
                itineraries.Id = Guid.NewGuid();

                itineraryInPackage.DeleteItinerary(itineraries.Id);

                itinerariesSevice.CreateItinerary(itineraries);

                
                for (int i = 0; i< Packages.Count; i++)
                {
                    ItineraryInPackage iip = new ItineraryInPackage
                    {
                        Id = Guid.NewGuid(),
                        ItineraryId = itineraries.Id,
                        TravelPackageId = Packages[i]
                    };

                    itineraryInPackage.CreateItineraryInPackage(iip);
                }

                
                return RedirectToAction(nameof(Index));
            }

            return View(itineraries);
        }

        // GET: Itineraries/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itineraries = itinerariesSevice.GetItinerariesById(id);
            if (itineraries == null)
            {
                return NotFound();
            }



            return View(itineraries);
        }

        // POST: Itineraries/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id, [Bind("Name,Description,DayNumber,Place,Image,ArivalTime,DepartutreTime,Id")] Itineraries itineraries)
        {
            if (id != itineraries.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    itinerariesSevice.UpdateItinerary(itineraries);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItinerariesExists(itineraries.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(itineraries);
        }

        // GET: Itineraries/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var itineraries = itinerariesSevice.GetItinerariesById(id);
            if (itineraries == null)
            {
                return NotFound();
            }

            return View(itineraries);
        }

        // POST: Itineraries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            itinerariesSevice.DeleteItinerary(id);
            return RedirectToAction(nameof(Index));
        }

        private bool ItinerariesExists(Guid id)
        {
            return itinerariesSevice.GetItinerariesById(id) != null;
        }
    }
}

TravelAgency.Web/Controllers/TravelPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TravelAgency.Domain.Enumeration;
using TravelAgency.Domain.Models;
using TravelAgency.Service.Interface;

namespace TravelAgency.Web.Controllers
{
    public class TravelPackagesController : Controller
    {
        private readonly ITravelPackagesService packagesService;

        public TravelPackagesController(ITravelPackagesService packagesService)
        {
            this.packagesService = packagesService;
        }

        // GET: TravelPackages
        public IActionResult Index()
        {
            return View(packagesService.ListAllPackages());
        }
        
        // GET: TravelPackages/Details/5
        public IActionResult Details(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            TravelPackages? travelPackage = packagesService?.GetPackage(id);
            if (travelPackage == null)
            {
                return NotFound();
            }

            return View(travelPackage);
        }

        // GET: TravelPackages/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["categories"] = GetCategoriesSelectList();

            return View();
        }

        // POST: TravelPackages/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create([Bind("Name, Description, Image, Duration, Seats, Price, StartDate, EndDate, Category")] TravelPackages package)
        {
            if (ModelState.IsValid)
            {
                packagesService.CreateNewPackage(package);
                return RedirectToAction(nameof(Index));
            }

            ViewData["categories"] = GetCategoriesSelectList(); 
            return View(package);
        }

        // GET: TravelPackages/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var travelPackage = packagesService.GetPackage(id);
            if (travelPackage == null)
            {
                return NotFound();
            }

            ViewData["categories"] = GetCategoriesSelectList(); // Populate dropdown with pre-selected category
            ViewData["category"] = travelPackage.Category;
            return View(travelPackage);
        }

        // POST: TravelPackages/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Guid id, [Bind("Id, Name, Description, Image, Duration, Seats, Price, StartDate, EndDate, Category")] TravelPackages package)
        {
            if (id != package.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                packagesService.UpdatePackage(package);
                return RedirectToAction(nameof(Index));
            }

            ViewData["categories"] = GetCategoriesSelectList(); // Repopulate dropdown on error
            return View(package);
        }

        // GET: TravelPackages/Delete/5
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }

            var travelPackage = packagesService.GetPackage(id);
            if (travelPackage == null)
            {
                return NotFound();
            }

            return View(travelPackage);
        }

        // POST: TravelPackages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(Guid id)
        {
            packagesService.DeletePackage(id);
            return RedirectToAction(nameof(Index));
        }

        // Helper method to get categories as SelectList
        private List<SelectListItem> GetCategoriesSelectList()
        {
            return Enum.GetValues(typeof(Category))
                       .Cast<Category>()
                       .Select(c => new SelectListItem
                       {
                           Text = c.ToString(),
                           Value = c.ToString()
                       }).ToList();
        }
    }
}

TravelAgency.Web/Pages/Shared/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace TravelAgency.Web.Pages.Shared
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

TravelAgency.Web/Pages/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelAgency</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TravelAgency.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">A&M Apartments</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TravelPackages" asp-action="Index">Travel Packages</a>
                        </li>
                        @if (User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Bookings" asp-action="Index">My Bookings</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Bookings" asp-action="Index">All Bookings</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Itineraries" asp-action="Index">Itineraries</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="text-white text-center py-5" style="background-color: #2c415e">
        <div class="container">
            <p class="mb-0">&copy; @DateTime.Now.Year Travel Agency. All rights reserved.</p>
            <ul class="list-unstyled">
                <li><a href="#" class="text-white">Privacy Policy</a> | <a href="#" class="text-white">Terms of Service</a></li>
            </ul>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>